project:
  output-dir: "_output"
  type: book

author:
  - name: Thomas Ranner
    email: T.Ranner@leeds.ac.uk
    affiliation: School of Computer Science, University of Leeds

book:
  title: "COMP2870 Theoretical Foundations: Linear Algebra"
  author: "Thomas Ranner"
  date: today
  date-format: "D MMMM YYYY"
  site-url: https://comp2870-2526.github.io/linear-algebra-notes/
  page-navigation: true
  search: true
  page-footer: "Copyright 2024-2025, Thomas Ranner and University of Leeds"
  repo-url: https://github.com/COMP2870-2526/linear-algebra-notes
  repo-actions: [edit, source, issue]
  downloads: [pdf]
  language: "en-GB"
  chapters:
    - index.qmd
    - src/lec02.qmd
    - src/lec03.qmd
    - src/lec04.qmd
    - src/lec05.qmd
    - src/lec06.qmd
    - src/lec07.qmd
    - src/lec08.qmd

toc: true
number-sections: true
callout-icon: false

format:
  html:
    navbar: true
    respect-user-color-scheme: true
    theme:
      light:
        - flatly
        - theorem.scss
      dark:
        - darkly
        - theorem.scss
    include-in-header: mathjax.html
  pdf: default

execute:
  freeze: auto
  cache: true
