project:
  output-dir: "_output"
  type: website

author:
  - name: Thomas Ranner
    email: T.Ranner@leeds.ac.uk
    affiliation: School of Computer Science, University of Leeds

#book:
#  title: "COMP2860 Theoretical Foundations: Linear Algebra"
#  author: "Thomas Ranner"
#  chapters:
#    - index.qmd
#    - src/lec01.qmd
#    - src/lec02.qmd
#    - src/lec04.qmd
#    - src/lec05.qmd
#    - src/lec06.qmd
#    - src/lec07.qmd
#    - src/lec08.qmd

website:
  title: "COMP2860 Theoretical Foundations: Linear Algebra"
  page-navigation: true
  search: true
  page-footer: "Copyright 2024, Thomas Ranner and University of Leeds"
  repo-url: "https://github.com/TODO"
  repo-actions: [edit, source, issue]

  sidebar:
    contents: src/*

toc: true
number-sections: true
callout-icon: false

format:
  html:
    navbar: true
    theme:
      light:
        - flatly
        - theorem.scss
      dark:
        - darkly
        - theorem.scss
    include-in-header: mathjax.html
  # pdf: default

execute:
  freeze: auto
  cache: true
